server:
  port: 8085

hm:
  db:
    database: hm-trade
  swagger:
    title: 星链商城交易服务接口文档
    desc: "星链商城交易服务接口文档"
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: zhj123456
    virtual-host: /
  redis:
    host: 127.0.0.1
    port: 6379

seata:
  enabled: true
  application-id: trade-service
  tx-service-group: hmall-tx-group
  data-source-proxy-mode: AT
  service:
    vgroup-mapping:
      hmall-tx-group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: file
  config:
    type: file
