server:
  port: 8081

hm:
  db:
    database: hm-item

  swagger:
    title: 星链商城商品服务接口文档
    description: "星链商城商品服务接口文档"
    package: com.hmall.item.controller
  
  elasticsearch:
    host: http://127.0.0.1:9200

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: zhj123456
    virtual-host: /

seata:
  enabled: true
  application-id: item-service
  tx-service-group: hmall-tx-group
  data-source-proxy-mode: AT
  service:
    vgroup-mapping:
      hmall-tx-group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: file
  config:
    type: file
